### ISSUE TITLE
New build &/ build instructions?

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [nirgoren/Eddienput#41]
Hey! I'd like to use Eddienput's recording features, but they're newer than the newest release (1.2). I fell down the rabbit hole trying to get it to build locally, but have yet to get a (working) build. Would it be possible to cut a new release from the current state of the project?

**Comment by Trial-In-Error** [comment]
... Ah. Github wasn't showing the build in the usual place because it's a preview build.

I think this issue is probably worth keeping open, though, to track making the project buildable from its lockfile.

**Comment by V-Cent** [comment]
For those that also want to build I made a quick run-down to get things working:
As mentioned [here](https://github.com/nirgoren/Eddienput/discussions/30) this project requires Python 3.7. I have 3.9 so I had to use that renaming hack to get both working to build the project. Anyways here it is:

Requirements: 
	Python 3.7 (Important! 3.8 and 3.9 will not work) (https://www.python.org/downloads/release/python-379/)
		Rec: rename exe to python37 and run everything (pip and pipenv) under python37 -m ...
	PyInstaller (pip), Pipenv(pip), Visual Studio 2019 (used 2022 and it worked)
	PyQt5 (pip), pynput (pip), XInput-Python (pip)
Clone Repo (git clone https://github.com/nirgoren/Eddienput.git --recurse-submodules)
Go into ViGEmClient and Build for Release
Go into vcontroller and Build for Release
On your terminal of choice:
	Install dependencies (python37 -m pipenv install)
	Enter into the project's virtualenv (python37 -m pipenv shell)
        Edit/Duplicate build.bat (I made a copy into altBuild.bat) and change the PyInstaller call to python37 -m PyInstaller ...
	Run .\altBuild.bat
Done

Not sure if you need the pipenv dependencies if you get the requirements beforehand, but I installed anyway because I'm not used to using PyInstaller much.

**Comment by echo-bravo-yahoo** [comment]
Ah, this is super useful! Sorry I didn't see it before. @nirgoren, would you welcome a PR that adds this to the README?

**Comment by nirgoren** [comment]
> Ah, this is super useful! Sorry I didn't see it before. @nirgoren, would you welcome a PR that adds this to the README?

I updated the project to use the more modern Poetry instead of Pipenv (and Python 3.12 instead of the now deprecated 3.7). Updated build instructions can now be found on the README.
